/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.gui;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import projectgui.*;

/**
 *
 * @author lenovoo
 */
public class Admin extends javax.swing.JFrame {

     TaskSwitchController SwitchController;
     
     MementoCareTaker careTaker;
     StringAccessor StringsAccess;
     AbstractFunction AbstractObject;
     
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        StringsAccess = new StringAccessor();
         careTaker = new MementoCareTaker();
        initComponents();
        jComboBox_UserType.addItem("Manager");
        
        jComboBox_UserType.addItem("Member");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton_AddTask = new javax.swing.JButton();
        jButton_UpdateTaskInfo = new javax.swing.JButton();
        jButton_DeleteTask = new javax.swing.JButton();
        jTextField_TaskID = new javax.swing.JTextField();
        jTextField_StartDate = new javax.swing.JTextField();
        jTextField_TaskName = new javax.swing.JTextField();
        jTextField_EndDate = new javax.swing.JTextField();
        jTextField_Status = new javax.swing.JTextField();
        jTextField_MemberNumber = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_MemberTaskID = new javax.swing.JTextField();
        jButton_AddMemberToTask = new javax.swing.JButton();
        jButton_DeleteMemberFromTask = new javax.swing.JButton();
        jTextField_MemberID = new javax.swing.JTextField();
        jComboBox_UserType = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonDeleteMyself = new javax.swing.JButton();
        TextField_NewEmail = new javax.swing.JTextField();
        Button_ChangeInfo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ShowTasks = new javax.swing.JTable();
        jButton_getTaskMembers = new javax.swing.JButton();
        TextField_NewPhone = new javax.swing.JTextField();
        TextField_NewPassword = new javax.swing.JTextField();
        jButtonUndo = new javax.swing.JButton();
        jButtonRedo = new javax.swing.JButton();
        Label_MemberNumber2 = new javax.swing.JLabel();
        Label_MemberNumber6 = new javax.swing.JLabel();
        Label_MemberNumber3 = new javax.swing.JLabel();
        Label_MemberNumber5 = new javax.swing.JLabel();
        Label_MemberNumber4 = new javax.swing.JLabel();
        jButton_ProjectBoard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 0)));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText(" Tasks ");

        jLabel4.setText("Task_ID");

        jLabel5.setText("Task_Name");

        jLabel6.setText("Start_Date");

        jLabel7.setText("End_Date");

        jLabel8.setText("Status");

        jLabel9.setText("Number_Member");

        jButton_AddTask.setText("ADD");
        jButton_AddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddTaskActionPerformed(evt);
            }
        });

        jButton_UpdateTaskInfo.setText("Update");
        jButton_UpdateTaskInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateTaskInfoActionPerformed(evt);
            }
        });

        jButton_DeleteTask.setText("DELETE");
        jButton_DeleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteTaskActionPerformed(evt);
            }
        });

        jTextField_TaskName.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_Status, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_TaskName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTextField_StartDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_EndDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_TaskID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_MemberNumber)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton_AddTask)
                        .addGap(39, 39, 39)
                        .addComponent(jButton_UpdateTaskInfo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_DeleteTask)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_TaskID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_TaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_MemberNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddTask)
                    .addComponent(jButton_UpdateTaskInfo)
                    .addComponent(jButton_DeleteTask))
                .addGap(30, 30, 30))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));

        jLabel2.setText(" Member");

        jLabel10.setText("Member ID");

        jLabel13.setText("Task ID");

        jButton_AddMemberToTask.setText("ADD");
        jButton_AddMemberToTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddMemberToTaskActionPerformed(evt);
            }
        });

        jButton_DeleteMemberFromTask.setText("DELETE");

        jTextField_MemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MemberIDActionPerformed(evt);
            }
        });

        jComboBox_UserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_UserType.setSelectedItem(null);
        jComboBox_UserType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_UserTypeItemStateChanged(evt);
            }
        });
        jComboBox_UserType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox_UserTypePropertyChange(evt);
            }
        });

        jLabel18.setText("Member Type");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_AddMemberToTask)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_MemberTaskID)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton_DeleteMemberFromTask)
                                        .addGap(0, 103, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_UserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(120, 120, 120)
                        .addComponent(jTextField_MemberID)))
                .addGap(90, 90, 90))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_MemberTaskID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_UserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddMemberToTask)
                    .addComponent(jButton_DeleteMemberFromTask))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));

        jLabel3.setText(" Resources");

        jLabel14.setText("Type");

        jLabel15.setText("SW");

        jLabel16.setText("HW");

        jCheckBox1.setText("OS");

        jCheckBox2.setText("IDE");

        jCheckBox3.setText("URL");

        jCheckBox4.setText("Memory");

        jButton7.setText("ADD");

        jButton8.setText("Update");

        jButton9.setText("DELETE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(29, 29, 29)
                                .addComponent(jCheckBox4))
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(27, 27, 27)
                .addComponent(jButton9)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jButtonDeleteMyself.setText("DELETEMyself");
        jButtonDeleteMyself.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteMyselfActionPerformed(evt);
            }
        });

        TextField_NewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NewEmailActionPerformed(evt);
            }
        });

        Button_ChangeInfo.setText("Change Your Information ");
        Button_ChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ChangeInfoActionPerformed(evt);
            }
        });

        jTable_ShowTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TaskID", "TaskName", "Start_date", "End_date", "Status", "MemberID"
            }
        ));
        jScrollPane2.setViewportView(jTable_ShowTasks);

        jButton_getTaskMembers.setText("Get selected task members");
        jButton_getTaskMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_getTaskMembersActionPerformed(evt);
            }
        });

        TextField_NewPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NewPhoneActionPerformed(evt);
            }
        });

        TextField_NewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NewPasswordActionPerformed(evt);
            }
        });

        jButtonUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gui/redo.PNG"))); // NOI18N
        jButtonUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });

        jButtonRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gui/undo.PNG"))); // NOI18N
        jButtonRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRedoActionPerformed(evt);
            }
        });

        Label_MemberNumber2.setText("Undo");

        Label_MemberNumber6.setText("Redo");

        Label_MemberNumber3.setText("New Email");

        Label_MemberNumber5.setText("New Mobile");

        Label_MemberNumber4.setText("New Password");

        jButton_ProjectBoard.setText("Project Board");
        jButton_ProjectBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProjectBoardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRedo)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Label_MemberNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton_getTaskMembers))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jButton_ProjectBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_MemberNumber3)
                                .addGap(45, 45, 45)
                                .addComponent(TextField_NewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_MemberNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_MemberNumber5)
                                    .addComponent(Label_MemberNumber4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextField_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonDeleteMyself))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextField_NewPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Button_ChangeInfo)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_MemberNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRedo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(TextField_NewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_MemberNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Label_MemberNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton_getTaskMembers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ProjectBoard)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button_ChangeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_NewPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_MemberNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TextField_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Label_MemberNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtonDeleteMyself)
                                        .addContainerGap())))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteMyselfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteMyselfActionPerformed
        
        MemberFactory factor = new MemberFactory();
        Member memberObj= factor.getmember();
      
        memberObj.remove();
        
    }//GEN-LAST:event_jButtonDeleteMyselfActionPerformed

    private void TextField_NewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NewEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NewEmailActionPerformed

    private void Button_ChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ChangeInfoActionPerformed
        // this design will be allways for normal members
        MemberFactory memberFactor = new MemberFactory();
           ArrayList<String> DataToUpdate= new ArrayList<String>();
        DataToUpdate.add(TextField_NewEmail.getText());
        DataToUpdate.add(TextField_NewPhone.getText());
        DataToUpdate.add(TextField_NewPassword.getText());
        Member memberObj = memberFactor.getmember();
        memberObj.setDataToBeUpdated(DataToUpdate);
        memberObj.update();
    }//GEN-LAST:event_Button_ChangeInfoActionPerformed

    private void jButton_AddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddTaskActionPerformed
        
        AbstractObject=new Task(jTextField_TaskID.getText(),jTextField_TaskName.getText(),jTextField_StartDate.getText(),jTextField_EndDate.getText(),jTextField_Status.getText(),jTextField_MemberNumber.getText());
        AbstractObject.add();
       
        careTaker.Save(AbstractObject,"AddTask");
        DefaultTableModel model=(DefaultTableModel)jTable_ShowTasks.getModel();
        String str[]=new String[]{jTextField_TaskID.getText(),jTextField_TaskName.getText(),jTextField_StartDate.getText(),jTextField_EndDate.getText(),jTextField_Status.getText(),jTextField_MemberNumber.getText()};
        model.addRow(str);
        
    }//GEN-LAST:event_jButton_AddTaskActionPerformed

    private void jButton_DeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteTaskActionPerformed
        careTaker.Save(AbstractObject,"DeleteTask");
        AbstractObject =new Task(jTextField_TaskID.getText(),jTextField_TaskName.getText(),jTextField_StartDate.getText(),jTextField_EndDate.getText(),jTextField_Status.getText(),jTextField_MemberNumber.getText());
        AbstractObject.remove();
        DefaultTableModel model=(DefaultTableModel)jTable_ShowTasks.getModel();  
        int RowNumber = Integer.valueOf(jTextField_TaskID.getText()) -1;
        model.removeRow(RowNumber);
        
    
    }//GEN-LAST:event_jButton_DeleteTaskActionPerformed

    private void jButton_UpdateTaskInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateTaskInfoActionPerformed
         careTaker.Save(AbstractObject,"UpdateTask");
        AbstractObject =new Task(jTextField_TaskID.getText(),jTextField_TaskName.getText(),jTextField_StartDate.getText(),jTextField_EndDate.getText(),jTextField_Status.getText(),jTextField_MemberNumber.getText());
        AbstractObject.update();
        
    }//GEN-LAST:event_jButton_UpdateTaskInfoActionPerformed

    private void jButton_AddMemberToTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddMemberToTaskActionPerformed
        MemberFactory factor = new MemberFactory();
        String choosedType = String.valueOf(jComboBox_UserType.getSelectedItem());
        Member memberObj = factor.getmember(choosedType);
        memberObj.AssignTask(jTextField_MemberID.getText(),jTextField_MemberTaskID.getText());
        AbstractObject = memberObj;
        AbstractObject.add();
        careTaker.Save(AbstractObject,"AssignMember");
        
    }//GEN-LAST:event_jButton_AddMemberToTaskActionPerformed

    private void jTextField_MemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MemberIDActionPerformed

    private void jButton_getTaskMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_getTaskMembersActionPerformed
     
        int row =jTable_ShowTasks.getSelectedRow();
        String IDRow = String.valueOf(jTable_ShowTasks.getValueAt(row, 5));
   
      Task taskObject = new Task();
      String MemberName = taskObject.getMembersNames(IDRow);
      
        final JFrame frameObjectToShowMemberName = new JFrame();
         frameObjectToShowMemberName.add(jButton_getTaskMembers);
        frameObjectToShowMemberName.pack();
        frameObjectToShowMemberName.setVisible(true);

           JOptionPane.showConfirmDialog(frameObjectToShowMemberName,MemberName);
            
    }//GEN-LAST:event_jButton_getTaskMembersActionPerformed

    private void TextField_NewPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NewPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NewPhoneActionPerformed

    private void TextField_NewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NewPasswordActionPerformed

    private void jButtonUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUndoActionPerformed
        RemoteControl controller = new RemoteControl();
        
        SwitchController = new TaskSwitchController(careTaker.restore());
        if((careTaker.getLastActionType()).equalsIgnoreCase("")){
            if((careTaker.getLastActionType()).equalsIgnoreCase("DeleteTask")){
                Redo redoObject = new Redo(SwitchController);
                controller.setCommand(redoObject);
                
            }
            else {
                if((careTaker.getLastActionType()).equalsIgnoreCase("AddTask")){
                Undo UndoObject = new Undo(SwitchController);
                controller.setCommand(UndoObject);
                DefaultTableModel model=(DefaultTableModel)jTable_ShowTasks.getModel();  
                int RowNumber = jTable_ShowTasks.getRowCount()-1;
                model.removeRow(RowNumber);    
              
            }
                else if((careTaker.getLastActionType()).equalsIgnoreCase("AssignMember")){
                Undo UndoObject = new Undo(SwitchController);
                controller.setCommand(UndoObject);
            }
            // remove relation
            }
            controller.ButtonControl();
          
        }

    }//GEN-LAST:event_jButtonUndoActionPerformed

    private void jButton_ProjectBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProjectBoardActionPerformed
    ProjectBoard projectBoard = new ProjectBoard();
    projectBoard.setVisible(true);
    }//GEN-LAST:event_jButton_ProjectBoardActionPerformed

    private void jButtonRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRedoActionPerformed
      
         RemoteControl controller = new RemoteControl();
      
        SwitchController = new TaskSwitchController(careTaker.RedoRestoredData());
       
       if(careTaker.getLastActionType()!=""){
            if((careTaker.getLastActionType()).equalsIgnoreCase("Delete")){
                Undo UndoObject = new Undo(SwitchController);
                controller.setCommand(UndoObject);
            }
            else{
                Redo RedoObject = new Redo(SwitchController);
                controller.setCommand(RedoObject);
            }
            controller.ButtonControl();
        }
        
    }//GEN-LAST:event_jButtonRedoActionPerformed

    private void jComboBox_UserTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_UserTypeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_UserTypeItemStateChanged

    private void jComboBox_UserTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox_UserTypePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_UserTypePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ChangeInfo;
    private javax.swing.JLabel Label_MemberNumber2;
    private javax.swing.JLabel Label_MemberNumber3;
    private javax.swing.JLabel Label_MemberNumber4;
    private javax.swing.JLabel Label_MemberNumber5;
    private javax.swing.JLabel Label_MemberNumber6;
    private javax.swing.JTextField TextField_NewEmail;
    private javax.swing.JTextField TextField_NewPassword;
    private javax.swing.JTextField TextField_NewPhone;
    private javax.swing.JComboBox comobox_Department;
    private javax.swing.JComboBox comobox_Department1;
    private javax.swing.JComboBox comobox_Department2;
    private javax.swing.JComboBox comobox_Department3;
    private javax.swing.JComboBox comobox_Department4;
    private javax.swing.JComboBox comobox_Department5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDeleteMyself;
    private javax.swing.JButton jButtonRedo;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JButton jButton_AddMemberToTask;
    private javax.swing.JButton jButton_AddTask;
    private javax.swing.JButton jButton_DeleteMemberFromTask;
    private javax.swing.JButton jButton_DeleteTask;
    private javax.swing.JButton jButton_ProjectBoard;
    private javax.swing.JButton jButton_UpdateTaskInfo;
    private javax.swing.JButton jButton_getTaskMembers;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox_UserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_ShowTasks;
    private javax.swing.JTextField jTextField_EndDate;
    private javax.swing.JTextField jTextField_MemberID;
    private javax.swing.JTextField jTextField_MemberNumber;
    private javax.swing.JTextField jTextField_MemberTaskID;
    private javax.swing.JTextField jTextField_StartDate;
    private javax.swing.JTextField jTextField_Status;
    private javax.swing.JTextField jTextField_TaskID;
    private javax.swing.JTextField jTextField_TaskName;
    // End of variables declaration//GEN-END:variables
}
