/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.gui;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import projectgui.*;
import projectgui.Task;


/**
 *
 * @author lenovoo
 */
public class CoreFunGUI extends javax.swing.JFrame
{
     TaskSwitchController SwitchController; 
     AbstractFunction AbstractObject;
     MementoCareTaker careTaker;
     StringAccessor StringsAccess;
   
        /**
     * Creates new form 
     */
    public CoreFunGUI(){
        StringsAccess = new StringAccessor();
        careTaker = new MementoCareTaker();
        initComponents();
        ShowMembersCurrentTasks();
      }
    
    
   public void ShowMembersCurrentTasks(){
   MemberFactory currentMember = new MemberFactory();
   Member memberObject = currentMember.getmember();
   FileFacade FileInterface = new FileFacade();
   ArrayList<Task> tasks =  FileInterface.getMemberTasks(memberObject.getMemberID());
   DefaultTableModel model=(DefaultTableModel)jTable_ShowTasks.getModel();
       for (Task task : tasks) {
           
        String str[]=new String[]{task.getTaskID(),task.getName(),task.getStartDate(),task.getEndDate(),task.getStatus(),task.getMemberID()};
        model.addRow(str);
      
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonUndo = new javax.swing.JButton();
        jButtonRedo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextField_TaskName = new javax.swing.JTextField();
        TextFieldToDate = new javax.swing.JTextField();
        TextFieldFromDate = new javax.swing.JTextField();
        Label_TaskName = new javax.swing.JLabel();
        Label_FromDate = new javax.swing.JLabel();
        LabelToDate = new javax.swing.JLabel();
        Label_MemberNumber = new javax.swing.JLabel();
        TextField_MemberNumber = new javax.swing.JTextField();
        Button_TaskAdd = new javax.swing.JButton();
        Button_TaskUpdate = new javax.swing.JButton();
        Button_TaskDelete = new javax.swing.JButton();
        Label_MemberNumber1 = new javax.swing.JLabel();
        TextField_Status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextField_TaskID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Label_ResourceType = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CheckBox_OS = new javax.swing.JCheckBox();
        CheckBox_IDE = new javax.swing.JCheckBox();
        CheckBox_Memory = new javax.swing.JCheckBox();
        Button_ResourceAdd = new javax.swing.JButton();
        CheckBox_URL = new javax.swing.JCheckBox();
        Button_ResourceDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        darkGray = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ShowTasks = new javax.swing.JTable();
        Button_ChangeInfo = new javax.swing.JButton();
        TextField_NewPhone = new javax.swing.JTextField();
        TextField_NewEmail = new javax.swing.JTextField();
        TextField_NewPassword = new javax.swing.JTextField();
        Label_MemberNumber2 = new javax.swing.JLabel();
        Label_MemberNumber3 = new javax.swing.JLabel();
        Label_MemberNumber4 = new javax.swing.JLabel();
        Label_MemberNumber5 = new javax.swing.JLabel();
        Label_MemberNumber6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gui/redo.PNG"))); // NOI18N
        jButtonUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });

        jButtonRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gui/undo.PNG"))); // NOI18N
        jButtonRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRedoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 0)));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("   Tasks");

        TextFieldFromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFromDateActionPerformed(evt);
            }
        });

        Label_TaskName.setText("   Task Name");

        Label_FromDate.setText("   From date");

        LabelToDate.setText("    To date");

        Label_MemberNumber.setText("   Status");

        TextField_MemberNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_MemberNumberActionPerformed(evt);
            }
        });

        Button_TaskAdd.setText("ADD");
        Button_TaskAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TaskAddActionPerformed(evt);
            }
        });

        Button_TaskUpdate.setText("Update");
        Button_TaskUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TaskUpdateActionPerformed(evt);
            }
        });

        Button_TaskDelete.setText("Delete");
        Button_TaskDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TaskDeleteActionPerformed(evt);
            }
        });

        Label_MemberNumber1.setText("Number Memmber");

        TextField_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_StatusActionPerformed(evt);
            }
        });

        jLabel2.setText("   Task Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_TaskAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(Button_TaskUpdate)
                        .addGap(61, 61, 61)
                        .addComponent(Button_TaskDelete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_FromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addComponent(Label_TaskName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(173, 173, 173))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextField_TaskID, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_MemberNumber1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextField_MemberNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelToDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TextField_TaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Label_MemberNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(108, 108, 108)
                                        .addComponent(TextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(307, 307, 307))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_TaskID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_TaskName)
                    .addComponent(TextField_TaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_FromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_MemberNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_MemberNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_MemberNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_TaskAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TaskUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TaskDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 0)));

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("  Resources");

        Label_ResourceType.setText("  Type");

        jLabel8.setText("SW");

        jLabel9.setText("HW");

        CheckBox_OS.setText("OS");

        CheckBox_IDE.setText("IDE");
        CheckBox_IDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_IDEActionPerformed(evt);
            }
        });

        CheckBox_Memory.setSelected(true);
        CheckBox_Memory.setText("Memory");

        Button_ResourceAdd.setText("ADD");
        Button_ResourceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ResourceAddActionPerformed(evt);
            }
        });

        CheckBox_URL.setText("URL");

        Button_ResourceDelete.setText("Delete");
        Button_ResourceDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ResourceDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Label_ResourceType, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_ResourceAdd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CheckBox_IDE, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CheckBox_OS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBox_Memory))
                            .addComponent(CheckBox_URL)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(Button_ResourceDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ResourceType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox_OS)
                    .addComponent(CheckBox_Memory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBox_IDE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBox_URL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_ResourceAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_ResourceDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));

        jLabel13.setText("shape");

        jCheckBox5.setText("Circle");

        jCheckBox6.setText("Rect");

        jLabel14.setText("Color");

        darkGray.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gui/red.PNG"))); // NOI18N
        darkGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkGrayActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gui/blue.PNG"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gui/ss.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(darkGray, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox6)
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darkGray, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTable_ShowTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TaskID", "TaskName", "Start_date", "End_date", "Status", "MemberID"
            }
        ));
        jScrollPane2.setViewportView(jTable_ShowTasks);

        Button_ChangeInfo.setText("Change Your Information ");
        Button_ChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ChangeInfoActionPerformed(evt);
            }
        });

        TextField_NewPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NewPhoneActionPerformed(evt);
            }
        });

        TextField_NewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NewEmailActionPerformed(evt);
            }
        });

        TextField_NewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NewPasswordActionPerformed(evt);
            }
        });

        Label_MemberNumber2.setText("Undo");

        Label_MemberNumber3.setText("Email");

        Label_MemberNumber4.setText("Password");

        Label_MemberNumber5.setText("Mobile");

        Label_MemberNumber6.setText("Redo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_MemberNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_MemberNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_MemberNumber4)
                                    .addComponent(Label_MemberNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 214, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Button_ChangeInfo)
                                .addGap(299, 299, 299))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_NewPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_NewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(Label_MemberNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(224, 224, 224))))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_MemberNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(Button_ChangeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_NewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_MemberNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextField_NewPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_MemberNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextField_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_MemberNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(Label_MemberNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCircleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCircleActionPerformed

    private void Button_TaskAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TaskAddActionPerformed
       
        AbstractObject=new Task(TextField_TaskID.getText(),TextField_TaskName.getText(),TextFieldFromDate.getText(),TextFieldToDate.getText(),TextField_Status.getText(),TextField_MemberNumber.getText());
        AbstractObject.add();
        careTaker.Save(AbstractObject,"AddTask");
        DefaultTableModel model=(DefaultTableModel)jTable_ShowTasks.getModel();
        String str[]=new String[]{TextField_TaskID.getText(),TextField_TaskName.getText(),TextFieldFromDate.getText(),TextFieldToDate.getText(),TextField_Status.getText(),TextField_MemberNumber.getText()};
        model.addRow(str);
      
    }//GEN-LAST:event_Button_TaskAddActionPerformed

    private void TextField_MemberNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_MemberNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_MemberNumberActionPerformed

    private void TextFieldFromDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFromDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFromDateActionPerformed

    private void TextField_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_StatusActionPerformed

    private void Button_TaskUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TaskUpdateActionPerformed
         careTaker.Save(AbstractObject,"UpdateTask");
      
        Task TaskUpdateObject =new Task(TextField_TaskID.getText(),TextField_TaskName.getText(),TextFieldFromDate.getText(),TextFieldToDate.getText(),TextField_Status.getText(),TextField_MemberNumber.getText());
        TaskUpdateObject.update();
        
    }//GEN-LAST:event_Button_TaskUpdateActionPerformed

    private void Button_TaskDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TaskDeleteActionPerformed
        careTaker.Save(AbstractObject,"DeleteTask");
        AbstractObject =new Task(TextField_TaskID.getText(),TextField_TaskName.getText(),TextFieldFromDate.getText(),TextFieldToDate.getText(),TextField_Status.getText(),TextField_MemberNumber.getText());
        AbstractObject.remove();
        DefaultTableModel model=(DefaultTableModel)jTable_ShowTasks.getModel();  
        int RowNumber = Integer.valueOf(TextField_TaskID.getText()) -1;
        model.removeRow(RowNumber);

    }//GEN-LAST:event_Button_TaskDeleteActionPerformed

    private void darkGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkGrayActionPerformed
        // TODO add your handling code here: 
//       OptionalDecorator object =new Color(frame1,"pink");
//       object.changeBackgroud();
        this.getContentPane().setBackground(Color.pink);
    }//GEN-LAST:event_darkGrayActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.blue);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void TextField_NewPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NewPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NewPhoneActionPerformed

    private void Button_ChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ChangeInfoActionPerformed
     // this design will be allways for normal members 
      MemberFactory memberFactor = new MemberFactory();
        ArrayList<String> DataToUpdate= new ArrayList<>();
        DataToUpdate.add(TextField_NewEmail.getText());
        DataToUpdate.add(TextField_NewPhone.getText());
        DataToUpdate.add(TextField_NewPassword.getText());
        Member memberObj = memberFactor.getmember();
        memberObj.setDataToBeUpdated(DataToUpdate);
        memberObj.update();
    }//GEN-LAST:event_Button_ChangeInfoActionPerformed

    private void TextField_NewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NewEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NewEmailActionPerformed

    private void TextField_NewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NewPasswordActionPerformed

    private void jButtonUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUndoActionPerformed
    RemoteControl controller = new RemoteControl();
        SwitchController = new TaskSwitchController(careTaker.restore());
        if(!(careTaker.getLastActionType()).equalsIgnoreCase("")){
            if((careTaker.getLastActionType()).equalsIgnoreCase("DeleteTask")){
                Redo redoObject = new Redo(SwitchController);
                controller.setCommand(redoObject);
            }
            else {
                if((careTaker.getLastActionType()).equalsIgnoreCase("AddTask")){
                Undo UndoObject = new Undo(SwitchController);
                controller.setCommand(UndoObject);
                DefaultTableModel model=(DefaultTableModel)jTable_ShowTasks.getModel();  
                int RowNumber = jTable_ShowTasks.getRowCount()-1;
                model.removeRow(RowNumber);    
              
            }
            // remove relation
            }
            controller.ButtonControl();
          
        }

    }//GEN-LAST:event_jButtonUndoActionPerformed

    private void jButtonRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRedoActionPerformed

        RemoteControl controller = new RemoteControl();
      
        SwitchController = new TaskSwitchController(careTaker.RedoRestoredData());
       
       if(careTaker.getLastActionType()!=""){
            if((careTaker.getLastActionType()).equalsIgnoreCase("DeleteTask")){
                Undo UndoObject = new Undo(SwitchController);
                controller.setCommand(UndoObject);
            }
            else{
                Redo RedoObject = new Redo(SwitchController);
                controller.setCommand(RedoObject);
            }
            controller.ButtonControl();
        }
         
    }//GEN-LAST:event_jButtonRedoActionPerformed

    private void CheckBox_IDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_IDEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_IDEActionPerformed

    private void Button_ResourceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ResourceAddActionPerformed
        // TODO add your handling code here:
        String task_id=TextField_TaskID.getText();
                    if(CheckBox_OS.isSelected())         
                        {
                           Resource resobject=new OS("OS",task_id);
                            resobject.add();
                        }
                    if(CheckBox_IDE.isSelected())
                        {
                            Resource resobject=new IDE("IDE",task_id);
                            resobject.add();
                        }
                    if(CheckBox_URL.isSelected())
                    {
                         Resource resobject=new URL("URL",task_id);
                        resobject.add();
                    }
                if(CheckBox_Memory.isSelected())
                    {
                         Resource resobject=new Memory("Memory",task_id);
                        resobject.add();
                    }
        
    }//GEN-LAST:event_Button_ResourceAddActionPerformed

    private void Button_ResourceDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ResourceDeleteActionPerformed
        // TODO add your handling code here:
        String task_id=TextField_TaskID.getText();
        if(CheckBox_OS.isSelected())         
         {
            Resource resobject=new OS("OS",task_id);
            resobject.update(task_id);
         }
                    if(CheckBox_IDE.isSelected())
                        {
                            Resource resobject=new IDE("IDE",task_id);
                            resobject.update(task_id);
                        }
                    if(CheckBox_URL.isSelected())
                    {
                         Resource resobject=new URL("URL",task_id);
                         resobject.update(task_id);
                    }
                if(CheckBox_Memory.isSelected())
                    {
                         Resource resobject=new Memory("Memory",task_id);
                        resobject.update(task_id);
                    }
    }//GEN-LAST:event_Button_ResourceDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoreFunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoreFunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoreFunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoreFunGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CoreFunGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ChangeInfo;
    private javax.swing.JButton Button_ResourceAdd;
    private javax.swing.JButton Button_ResourceDelete;
    private javax.swing.JButton Button_TaskAdd;
    private javax.swing.JButton Button_TaskDelete;
    private javax.swing.JButton Button_TaskUpdate;
    private javax.swing.JCheckBox CheckBox_IDE;
    private javax.swing.JCheckBox CheckBox_Memory;
    private javax.swing.JCheckBox CheckBox_OS;
    private javax.swing.JCheckBox CheckBox_URL;
    private javax.swing.JLabel LabelToDate;
    private javax.swing.JLabel Label_FromDate;
    private javax.swing.JLabel Label_MemberNumber;
    private javax.swing.JLabel Label_MemberNumber1;
    private javax.swing.JLabel Label_MemberNumber2;
    private javax.swing.JLabel Label_MemberNumber3;
    private javax.swing.JLabel Label_MemberNumber4;
    private javax.swing.JLabel Label_MemberNumber5;
    private javax.swing.JLabel Label_MemberNumber6;
    private javax.swing.JLabel Label_ResourceType;
    private javax.swing.JLabel Label_TaskName;
    private javax.swing.JTextField TextFieldFromDate;
    private javax.swing.JTextField TextFieldToDate;
    private javax.swing.JTextField TextField_MemberNumber;
    private javax.swing.JTextField TextField_NewEmail;
    private javax.swing.JTextField TextField_NewPassword;
    private javax.swing.JTextField TextField_NewPhone;
    private javax.swing.JTextField TextField_Status;
    private javax.swing.JTextField TextField_TaskID;
    private javax.swing.JTextField TextField_TaskName;
    private javax.swing.JButton darkGray;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonRedo;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_ShowTasks;
    // End of variables declaration//GEN-END:variables
}
