/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.gui;


import java.util.ArrayList;
import javax.swing.*;
import projectgui.*;

/**
 *
 * @author lenovoo
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        jLabel_ShowLoginErorr.setVisible(false);
        CoreFunctionality InterfaceObj = new CoreFunctionality();
        ArrayList<JComboBox> DateInfo = new ArrayList<JComboBox>();
       DateInfo=  InterfaceObj.GetRegistertationDate(ComboBox_Day,ComboBox_Month,ComboBox_Year);
        ComboBox_Day = DateInfo.get(0);
        ComboBox_Month = DateInfo.get(1);
        ComboBox_Year = DateInfo.get(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MyGroup = new javax.swing.ButtonGroup();
        MemberType = new javax.swing.ButtonGroup();
        Button_SignUp = new javax.swing.JButton();
        Button_SignIn = new javax.swing.JButton();
        jLabel_ID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtBox_FirstName = new javax.swing.JTextField();
        TxtBox_LastName = new javax.swing.JTextField();
        TxtBox_Email = new javax.swing.JTextField();
        TxtBox_Phone = new javax.swing.JTextField();
        ComboBox_Year = new javax.swing.JComboBox();
        ComboBox_Month = new javax.swing.JComboBox();
        ComboBox_Day = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        RadioButton_Admin = new javax.swing.JRadioButton();
        RadioButton_Member = new javax.swing.JRadioButton();
        TextBox_SignInEmail = new javax.swing.JTextField();
        TextBox_SignInpassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        RadioButton_Male1 = new javax.swing.JRadioButton();
        RadioButton_Female1 = new javax.swing.JRadioButton();
        TxtBox_Password = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtBox_MemberID = new javax.swing.JTextField();
        jLabel_ShowLoginErorr = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(getBackground());
        setUndecorated(true);

        Button_SignUp.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        Button_SignUp.setForeground(new java.awt.Color(51, 51, 255));
        Button_SignUp.setText("Sign Up");
        Button_SignUp.setActionCommand("SignUp");
        Button_SignUp.setName("signUp"); // NOI18N
        Button_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SignUpActionPerformed(evt);
            }
        });

        Button_SignIn.setForeground(new java.awt.Color(51, 51, 255));
        Button_SignIn.setText("Sign In");
        Button_SignIn.setName("signIn"); // NOI18N
        Button_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SignInActionPerformed(evt);
            }
        });

        jLabel_ID.setText("ID");

        jLabel2.setText("  Last Name");

        jLabel3.setText("     Email");

        jLabel4.setText("Password");

        jLabel5.setText("  BirthDay");

        jLabel6.setText("Member Type");
        jLabel6.setToolTipText("");

        TxtBox_FirstName.setName("TxtFirstName"); // NOI18N
        TxtBox_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox_FirstNameActionPerformed(evt);
            }
        });

        TxtBox_LastName.setName("TxtLastName"); // NOI18N

        TxtBox_Email.setName("TxtEmail"); // NOI18N

        TxtBox_Phone.setName("TxtPhone"); // NOI18N

        ComboBox_Year.setName("comoYear"); // NOI18N
        ComboBox_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_YearActionPerformed(evt);
            }
        });

        ComboBox_Month.setName("comoMonth"); // NOI18N

        ComboBox_Day.setName("comoBoxDay"); // NOI18N
        ComboBox_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_DayActionPerformed(evt);
            }
        });

        MemberType.add(RadioButton_Admin);
        RadioButton_Admin.setText("Admin");
        RadioButton_Admin.setName("male"); // NOI18N
        RadioButton_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_AdminActionPerformed(evt);
            }
        });

        MemberType.add(RadioButton_Member);
        RadioButton_Member.setText("Member");
        RadioButton_Member.setName("female"); // NOI18N
        RadioButton_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_MemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadioButton_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButton_Member)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton_Admin)
                    .addComponent(RadioButton_Member, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TextBox_SignInEmail.setName("Txtemail1"); // NOI18N

        TextBox_SignInpassword.setName("Txtpassword1"); // NOI18N

        jLabel7.setText("Email ");

        jLabel8.setText("Password");

        jLabel9.setText("Day");

        jLabel10.setText("Month");

        jLabel11.setText("Year");

        MyGroup.add(RadioButton_Male1);
        RadioButton_Male1.setText("Male");
        RadioButton_Male1.setName("male"); // NOI18N
        RadioButton_Male1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_Male1ActionPerformed(evt);
            }
        });

        MyGroup.add(RadioButton_Female1);
        RadioButton_Female1.setSelected(true);
        RadioButton_Female1.setText("Female");
        RadioButton_Female1.setName("female"); // NOI18N
        RadioButton_Female1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_Female1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadioButton_Male1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButton_Female1)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton_Male1)
                    .addComponent(RadioButton_Female1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TxtBox_Password.setName("TxtPhone"); // NOI18N

        jLabel12.setText("     Phone");

        jLabel13.setText("   Gender");
        jLabel13.setToolTipText("");

        TxtBox_MemberID.setName("TxtFirstName"); // NOI18N
        TxtBox_MemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBox_MemberIDActionPerformed(evt);
            }
        });

        jLabel_ShowLoginErorr.setText("Your Email or Password is invalid please try again "); // NOI18N

        jLabel15.setText("  First Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextBox_SignInEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(TextBox_SignInpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Button_SignIn)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(Button_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(0, 725, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtBox_MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_ShowLoginErorr, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtBox_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBox_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBox_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBox_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBox_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(731, 731, 731))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(987, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextBox_SignInpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextBox_SignInEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(Button_SignIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox_MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ShowLoginErorr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtBox_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(TxtBox_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtBox_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBox_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtBox_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(Button_SignUp)
                .addGap(148, 148, 148))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(453, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(271, 271, 271)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButton_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_MemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_MemberActionPerformed

    private void RadioButton_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_AdminActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_RadioButton_AdminActionPerformed

    private void ComboBox_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_YearActionPerformed

    private void Button_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SignInActionPerformed
    Proxi AdminProxi = new Proxi();
    boolean adminAuthonticationChecker = AdminProxi.CheckAuthonticationForAdmin(TextBox_SignInEmail.getText(),TextBox_SignInpassword.getText());
    if(adminAuthonticationChecker == true){
    Admin adminGUI = new Admin();
    adminGUI.setVisible(true);
    this.dispose();
    }    
    else{
    boolean memberAuthonticationChecker = AdminProxi.CheckAuthonticationForMember(TextBox_SignInEmail.getText(),TextBox_SignInpassword.getText());    
    if(memberAuthonticationChecker == true){
    CoreFunGUI memberTaskBoardGUI = new CoreFunGUI();
    memberTaskBoardGUI.setVisible(true);
    this.dispose();
    }
    else{
          jLabel_ShowLoginErorr.setVisible(true);
    }
    }
    }//GEN-LAST:event_Button_SignInActionPerformed

    private void ComboBox_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_DayActionPerformed

    private void Button_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SignUpActionPerformed
        // TODO add your handling code here:
      RegisterationFactory factorObject = new RegisterationFactory(TxtBox_MemberID.getText(),TxtBox_FirstName.getText(),TxtBox_LastName.getText(),TxtBox_Email.getText(),TxtBox_Phone.getText(),TxtBox_Password.getText(),RadioButton_Admin);
      
       registration regObject= factorObject.getregister();
        regObject.setData();
        MemberFactory memberFactor = new MemberFactory();
        Member YourMember = memberFactor.getmember();
       if(YourMember.MemberType == "ProjectManager"){
      ProjectBoard AdminGUIobject = new ProjectBoard();
      AdminGUIobject.setVisible(true);
      this.dispose();
       }
       else{
        CoreFunGUI HomeObject = new CoreFunGUI();
        HomeObject.setVisible(true);
        this.dispose();
       }
        
    }//GEN-LAST:event_Button_SignUpActionPerformed

    private void TxtBox_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox_FirstNameActionPerformed

    private void RadioButton_Male1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_Male1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_Male1ActionPerformed

    private void RadioButton_Female1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_Female1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_Female1ActionPerformed

    private void TxtBox_MemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBox_MemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBox_MemberIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_SignIn;
    private javax.swing.JButton Button_SignUp;
    private javax.swing.JComboBox ComboBox_Day;
    private javax.swing.JComboBox ComboBox_Month;
    private javax.swing.JComboBox ComboBox_Year;
    private javax.swing.ButtonGroup MemberType;
    private javax.swing.ButtonGroup MyGroup;
    private javax.swing.JRadioButton RadioButton_Admin;
    private javax.swing.JRadioButton RadioButton_Female1;
    private javax.swing.JRadioButton RadioButton_Male1;
    private javax.swing.JRadioButton RadioButton_Member;
    private javax.swing.JTextField TextBox_SignInEmail;
    private javax.swing.JTextField TextBox_SignInpassword;
    private javax.swing.JTextField TxtBox_Email;
    private javax.swing.JTextField TxtBox_FirstName;
    private javax.swing.JTextField TxtBox_LastName;
    private javax.swing.JTextField TxtBox_MemberID;
    private javax.swing.JTextField TxtBox_Password;
    private javax.swing.JTextField TxtBox_Phone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_ShowLoginErorr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
